name: ISL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - islp
    - matplotlib
    - seaborn
    - pandas
    - statsmodels
    - scikit-learn
    - jupyter
    - nbformat
